### PR TITLE
Add pooling, remove FileSource from GL.prototype

### LINKED ISSUE #37: new TileSource clobbers global FileSource
Ran into this testing the [`pool`](https://github.com/mapbox/tilelive-gl/compare/pool) branch.

gl.test.js
```
var fileSource = new mbgl.FileSource();
fileSource.request = function(req) {
    req.respond(null, { data: new Buffer(0) });
};
fileSource.cancel = function() {};

var GL = TileSource(fileSource);
```

concurrency.test.js and render.test.js both using [`./lib/fs`](https://github.com/mapbox/tilelive-gl/blob/master/test/lib/fs.js)
```
var GL = TileSource(require('./lib/fs'));
```

Somehow the `FileSource` from `gl.test.js` is being using when running the tests in `render.test.js`, resulting in RapidJSON errors parsing a file with no content. Verified this by changing the response to `new Buffer('{}')` and the error running `render.test.js` changes too.

/cc @jfirebaugh @bsudekum

### PR DESCRIPTION
**Pull request by mikemorris**
Previously #36, fixes #37 

/cc @bsudekum

### CODE REVIEW

**Comment by mikemorris** [comment]
Waiting on review/merge of https://github.com/mapbox/node-mapbox-gl-native/pull/143 before merging this.

**Comment by jfirebaugh** [comment]
I'm a bit confused about the motivation here. From #36:

> I added this here so that multiple requests can come into tilelive-gl. Somewhere, concurrency needs to be handled and from what I'm seeing, we're not adding it node-mapbox-gl-native.

To be clear: node-mapbox-gl-native is supposed to be safe to use concurrently: you should be able to make concurrent multiple calls to `map.render()` and everything should work. If this is not the case, it's a bug in node-mapbox-gl-native.

So, let's not confuse concurrency-safety with pooling for performance reasons.

@mikemorris - were you able to determine *why* the additional test in 61271098a88f20e3d9d82ce73b8edf8b88e28cd2 was failing? Was is because of #37?

**Comment by jfirebaugh** [comment]
Per https://github.com/mapbox/mapbox-gl-native/pull/1799#issuecomment-118929132, do we need to segment the pool on pixel ratio as well?

**Comment by mikemorris** [comment]
> You should be able to make concurrent multiple calls to `map.render()` and everything should work.

AFAIK this is not the case. Concurrent calls to `map.render()` from the same `NodeMap` previously [threw a JavaScript error](https://github.com/mapbox/node-mapbox-gl-native/blob/a9495844aae7da45d047de1320c0e0ec87742e43/src/node_map.cpp#L97-L99) and now hit a [C++ assertion failure](https://github.com/mapbox/gl-maps/issues/5#issuecomment-104736427) because [`mbgl::map::isRendering`](https://github.com/mapbox/mapbox-gl-native/blob/c5b124f7275625993c9cb9369166490d520440ac/src/mbgl/map/map.cpp#L166-L168) and the corresponding checks in node-mbgl were removed.

The concurrency test in https://github.com/mapbox/tilelive-gl/commit/61271098a88f20e3d9d82ce73b8edf8b88e28cd2 was failing because of `Assertion failed: (!nodeMap->callback)` https://github.com/mapbox/gl-maps/issues/5#issuecomment-123499545.

If concurrent calls to `map.render()` are now possible, we'll need to change how node-mbgl retains the callback for a render.

> do we need to segment the pool on pixel ratio as well?

I was planning to segment the LRU cache downstream on pixel ratio, and add a check during rendering to ensure that the attached View (https://github.com/mapbox/node-mapbox-gl-native/pull/144), has the same pixel ratio as the `RenderOptions` argument, and throw an error if this is not the case.

**Comment by jfirebaugh** [comment]
> > You should be able to make concurrent multiple calls to map.render() and everything should work.
> AFAIK this is not the case.

Hmm, didn't we have a render queue in node-mbgl at one point? I remember @kkaefer thought this was an important thing to support and I tend to agree.

**Comment by mikemorris** [comment]
@jfirebaugh @kkaefer dropped the render queue in https://github.com/mapbox/node-mapbox-gl-native/commit/8c6f71fdb26a4d7a4e2743d3661ff53adbf1658b

**Comment by jfirebaugh** [comment]
@kkaefer Can you comment here? Do you no longer think that node-mbgl should handle concurrency?

**Comment by kkaefer** [comment]
@jfirebaugh sorry for not responding here earlier. The queue implemented in native C++ was dropped, because it's easier to implement this in JavaScript code, e.g. by using the node-pool plugin. Instead of having a queue on every map object, we only allow one concurrent operation per map object (but multiple map objects can be active at the same time, of course). When the pool of available Map objects is exhausted, node-pool does the queueing for us for free.

**Comment by mikemorris** [comment]
> When the pool of available Map objects is exhausted, node-pool does the queueing for us for free.

Yea, this is what @bsudekum discovered and it works pretty well. We just need to bring back an actual JavaScript error when attempting to render concurrently instead of segfaulting.

**Comment by jfirebaugh** [comment]
This is now being handled in a downstream component.

**Pull request closed without merging**
